run:
  concurrency: 4
  timeout: 3m
  go: "1.21"
  tests: false

linters:
  disable-all: true
  enable:
    - errcheck
    - gomodguard
    - cyclop
    - gocritic
    - goconst
    - whitespace
    - unused
    - varnamelen
    - funlen
    - goimports
    - lll
    - varnamelen
    - funlen

linters-settings:
  cyclop:
    max-complexity: 11
  funlen:
    lines: 100

severity:
  default-severity: error
