version: "2"
run:
  concurrency: 4
  go: "1.25.4"
  tests: false
linters:
  default: none
  enable:
    - cyclop
    - errcheck
    - funlen
    - goconst
    - gocritic
    - gomodguard
    - lll
    - unused
    - varnamelen
    - whitespace
  settings:
    cyclop:
      max-complexity: 11
    funlen:
      lines: 100
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
severity:
  default: error
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
