// Code generated by MockGen. DO NOT EDIT.
// Source: config/reader.go
//
// Generated by this command:
//
//	mockgen -source=config/reader.go -destination=config/reader_mock.go -package=config
//

// Package config is a generated GoMock package.
package config

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockReaderStrategy is a mock of ReaderStrategy interface.
type MockReaderStrategy struct {
	ctrl     *gomock.Controller
	recorder *MockReaderStrategyMockRecorder
	isgomock struct{}
}

// MockReaderStrategyMockRecorder is the mock recorder for MockReaderStrategy.
type MockReaderStrategyMockRecorder struct {
	mock *MockReaderStrategy
}

// NewMockReaderStrategy creates a new mock instance.
func NewMockReaderStrategy(ctrl *gomock.Controller) *MockReaderStrategy {
	mock := &MockReaderStrategy{ctrl: ctrl}
	mock.recorder = &MockReaderStrategyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReaderStrategy) EXPECT() *MockReaderStrategyMockRecorder {
	return m.recorder
}

// Read mocks base method.
func (m *MockReaderStrategy) Read(filename string) (Cfg, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", filename)
	ret0, _ := ret[0].(Cfg)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockReaderStrategyMockRecorder) Read(filename any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockReaderStrategy)(nil).Read), filename)
}
