serverPort: 8080

routes:
  - method: GET
    host: http://localhost:8081
    path: /route-one
    headers:
      - xTestHeader: TestHeaderValue
    body:
      - testKey: testValue
    passWithRequestHeaders: true,
    passWithRequestBody: true,

  - method: GET
    path: /route-two
    mock:
      headers:
        - xTestHeader: TestHeaderValue
      bodyString: "OK"
      status: 200

  - method: GET
    path: /route-three
    mock:
      headers:
        - xTestHeader: TestHeaderValue
      body:
        - testKey: testValue
      status: 200

concurrency:
  routeCreatorLimit: 5
