// Code generated by MockGen. DO NOT EDIT.
// Source: cmd/create.go
//
// Generated by this command:
//
//	mockgen -source=cmd/create.go -destination=cmd/create_mock.go -package=cmd
//

// Package cmd is a generated GoMock package.
package cmd

import (
	config "inzibat/config"
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFormRunner is a mock of FormRunner interface.
type MockFormRunner struct {
	ctrl     *gomock.Controller
	recorder *MockFormRunnerMockRecorder
	isgomock struct{}
}

// MockFormRunnerMockRecorder is the mock recorder for MockFormRunner.
type MockFormRunnerMockRecorder struct {
	mock *MockFormRunner
}

// NewMockFormRunner creates a new mock instance.
func NewMockFormRunner(ctrl *gomock.Controller) *MockFormRunner {
	mock := &MockFormRunner{ctrl: ctrl}
	mock.recorder = &MockFormRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFormRunner) EXPECT() *MockFormRunnerMockRecorder {
	return m.recorder
}

// GetBool mocks base method.
func (m *MockFormRunner) GetBool(key string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBool", key)
	ret0, _ := ret[0].(bool)
	return ret0
}

// GetBool indicates an expected call of GetBool.
func (mr *MockFormRunnerMockRecorder) GetBool(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBool", reflect.TypeOf((*MockFormRunner)(nil).GetBool), key)
}

// GetString mocks base method.
func (m *MockFormRunner) GetString(key string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetString", key)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetString indicates an expected call of GetString.
func (mr *MockFormRunnerMockRecorder) GetString(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetString", reflect.TypeOf((*MockFormRunner)(nil).GetString), key)
}

// Run mocks base method.
func (m *MockFormRunner) Run() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run")
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockFormRunnerMockRecorder) Run() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockFormRunner)(nil).Run))
}

// MockHeadersCollector is a mock of HeadersCollector interface.
type MockHeadersCollector struct {
	ctrl     *gomock.Controller
	recorder *MockHeadersCollectorMockRecorder
	isgomock struct{}
}

// MockHeadersCollectorMockRecorder is the mock recorder for MockHeadersCollector.
type MockHeadersCollectorMockRecorder struct {
	mock *MockHeadersCollector
}

// NewMockHeadersCollector creates a new mock instance.
func NewMockHeadersCollector(ctrl *gomock.Controller) *MockHeadersCollector {
	mock := &MockHeadersCollector{ctrl: ctrl}
	mock.recorder = &MockHeadersCollectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHeadersCollector) EXPECT() *MockHeadersCollectorMockRecorder {
	return m.recorder
}

// Collect mocks base method.
func (m *MockHeadersCollector) Collect() (http.Header, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Collect")
	ret0, _ := ret[0].(http.Header)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Collect indicates an expected call of Collect.
func (mr *MockHeadersCollectorMockRecorder) Collect() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Collect", reflect.TypeOf((*MockHeadersCollector)(nil).Collect))
}

// MockBodyCollector is a mock of BodyCollector interface.
type MockBodyCollector struct {
	ctrl     *gomock.Controller
	recorder *MockBodyCollectorMockRecorder
	isgomock struct{}
}

// MockBodyCollectorMockRecorder is the mock recorder for MockBodyCollector.
type MockBodyCollectorMockRecorder struct {
	mock *MockBodyCollector
}

// NewMockBodyCollector creates a new mock instance.
func NewMockBodyCollector(ctrl *gomock.Controller) *MockBodyCollector {
	mock := &MockBodyCollector{ctrl: ctrl}
	mock.recorder = &MockBodyCollectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBodyCollector) EXPECT() *MockBodyCollectorMockRecorder {
	return m.recorder
}

// Collect mocks base method.
func (m *MockBodyCollector) Collect() (config.HttpBody, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Collect")
	ret0, _ := ret[0].(config.HttpBody)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Collect indicates an expected call of Collect.
func (mr *MockBodyCollectorMockRecorder) Collect() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Collect", reflect.TypeOf((*MockBodyCollector)(nil).Collect))
}

// MockBodyStringCollector is a mock of BodyStringCollector interface.
type MockBodyStringCollector struct {
	ctrl     *gomock.Controller
	recorder *MockBodyStringCollectorMockRecorder
	isgomock struct{}
}

// MockBodyStringCollectorMockRecorder is the mock recorder for MockBodyStringCollector.
type MockBodyStringCollectorMockRecorder struct {
	mock *MockBodyStringCollector
}

// NewMockBodyStringCollector creates a new mock instance.
func NewMockBodyStringCollector(ctrl *gomock.Controller) *MockBodyStringCollector {
	mock := &MockBodyStringCollector{ctrl: ctrl}
	mock.recorder = &MockBodyStringCollectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBodyStringCollector) EXPECT() *MockBodyStringCollectorMockRecorder {
	return m.recorder
}

// Collect mocks base method.
func (m *MockBodyStringCollector) Collect() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Collect")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Collect indicates an expected call of Collect.
func (mr *MockBodyStringCollectorMockRecorder) Collect() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Collect", reflect.TypeOf((*MockBodyStringCollector)(nil).Collect))
}

// MockMockResponseFormCreator is a mock of MockResponseFormCreator interface.
type MockMockResponseFormCreator struct {
	ctrl     *gomock.Controller
	recorder *MockMockResponseFormCreatorMockRecorder
	isgomock struct{}
}

// MockMockResponseFormCreatorMockRecorder is the mock recorder for MockMockResponseFormCreator.
type MockMockResponseFormCreatorMockRecorder struct {
	mock *MockMockResponseFormCreator
}

// NewMockMockResponseFormCreator creates a new mock instance.
func NewMockMockResponseFormCreator(ctrl *gomock.Controller) *MockMockResponseFormCreator {
	mock := &MockMockResponseFormCreator{ctrl: ctrl}
	mock.recorder = &MockMockResponseFormCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMockResponseFormCreator) EXPECT() *MockMockResponseFormCreatorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMockResponseFormCreator) Create() (*config.FakeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create")
	ret0, _ := ret[0].(*config.FakeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockMockResponseFormCreatorMockRecorder) Create() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMockResponseFormCreator)(nil).Create))
}

// MockClientRequestFormCreator is a mock of ClientRequestFormCreator interface.
type MockClientRequestFormCreator struct {
	ctrl     *gomock.Controller
	recorder *MockClientRequestFormCreatorMockRecorder
	isgomock struct{}
}

// MockClientRequestFormCreatorMockRecorder is the mock recorder for MockClientRequestFormCreator.
type MockClientRequestFormCreatorMockRecorder struct {
	mock *MockClientRequestFormCreator
}

// NewMockClientRequestFormCreator creates a new mock instance.
func NewMockClientRequestFormCreator(ctrl *gomock.Controller) *MockClientRequestFormCreator {
	mock := &MockClientRequestFormCreator{ctrl: ctrl}
	mock.recorder = &MockClientRequestFormCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientRequestFormCreator) EXPECT() *MockClientRequestFormCreatorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockClientRequestFormCreator) Create() (*config.RequestTo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create")
	ret0, _ := ret[0].(*config.RequestTo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockClientRequestFormCreatorMockRecorder) Create() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockClientRequestFormCreator)(nil).Create))
}
