// Code generated by MockGen. DO NOT EDIT.
// Source: cmd/create.go
//
// Generated by this command:
//
//	mockgen -source=cmd/create.go -destination=cmd/create_mock.go -package=cmd
//

// Package cmd is a generated GoMock package.
package cmd
