// Code generated by MockGen. DO NOT EDIT.
// Source: cmd/form_builder/form_collector.go
//
// Generated by this command:
//
//	mockgen -source=cmd/form_builder/form_collector.go -destination=cmd/form_builder/form_runner_mock.go -package=form_builder
//

// Package form_builder is a generated GoMock package.
package form_builder

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFormRunner is a mock of FormRunner interface.
type MockFormRunner struct {
	ctrl     *gomock.Controller
	recorder *MockFormRunnerMockRecorder
	isgomock struct{}
}

// MockFormRunnerMockRecorder is the mock recorder for MockFormRunner.
type MockFormRunnerMockRecorder struct {
	mock *MockFormRunner
}

// NewMockFormRunner creates a new mock instance.
func NewMockFormRunner(ctrl *gomock.Controller) *MockFormRunner {
	mock := &MockFormRunner{ctrl: ctrl}
	mock.recorder = &MockFormRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFormRunner) EXPECT() *MockFormRunnerMockRecorder {
	return m.recorder
}

// GetBool mocks base method.
func (m *MockFormRunner) GetBool(key string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBool", key)
	ret0, _ := ret[0].(bool)
	return ret0
}

// GetBool indicates an expected call of GetBool.
func (mr *MockFormRunnerMockRecorder) GetBool(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBool", reflect.TypeOf((*MockFormRunner)(nil).GetBool), key)
}

// GetString mocks base method.
func (m *MockFormRunner) GetString(key string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetString", key)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetString indicates an expected call of GetString.
func (mr *MockFormRunnerMockRecorder) GetString(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetString", reflect.TypeOf((*MockFormRunner)(nil).GetString), key)
}

// Run mocks base method.
func (m *MockFormRunner) Run() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run")
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockFormRunnerMockRecorder) Run() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockFormRunner)(nil).Run))
}
